# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.3
loom_version=1.11-SNAPSHOT
fabric_version=0.134.0+1.21.9

# Mod Properties
mod_version=2.0.0-beta.5.2+1.21.9
# the X.dev means that this is not yet a finished beta version, which means that:
# beta.X is not yet finished. you could say it's a beta of the beta version
# (but without a precise name, since it's not meant to be used by anyone)

# 1.21-1.21.1
maven_group=ahud.adaptivehud
archives_base_name=adaptivehud